name: model-training

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 3: Run the test script
      - name: Run the test script
        run: |
          python wine_linear_regression_test.py
          cat metrics.txt

      # Step 4: Generate a report and send a comment
      - name: Generate report and post comment
        run: |
          cat metrics.txt >> report.md
          cml-send-comment report.md
