name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the model test script
        run: |
          python wine_linear_regression_test.py
      - name: Display metrics
        run: cat metrics.txt
      - name: Generate report
        run: |
          cat metrics.txt >> report.md
          cml-send-comment report.md
