name: model-training
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @iterative/cml

      - name: Run Model Training
        run: |
          python wine_linear_regression_test.py
          cat metrics.txt

      - name: Generate and Send Report
        run: |
          cat metrics.txt >> report.md
          cml-send-comment report.md
