name: model-training
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Set up CML
      - uses: iterative/setup-cml@v2

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the model test script
      - name: Run Model Training
        run: |
          python wine_linear_regression_test.py

      # Step 5: Display the metrics
      - name: Display metrics
        run: cat metrics.txt

      # Step 6: Generate and Send Report
      - name: Generate and Send Report
        run: |
          cat metrics.txt >> report.md
          cml-send-comment report.md
