name: model-training

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Step 3: Install CML
      - name: Install CML
        run: |
          npm install -g git+https://github.com/iterative/cml.git

      # Step 4: Run the test script
      - name: Run the test script
        run: |
          python wine_linear_regression_test.py
          cat metrics.txt

      # Step 5: Generate report and post comment
      - name: Generate report and post comment
        run: |
          cat metrics.txt >> report.md
          cml-send-comment report.md
